# Generated by Django 5.1.3 on 2025-05-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnTorrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to='torrents/'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='magnet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
